"""empty message

Revision ID: d04c14dcc5e6
Revises: 
Create Date: 2024-06-29 20:44:01.590235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd04c14dcc5e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('img_categories',
    sa.Column('cate_id', sa.Integer(), nullable=False),
    sa.Column('cate_name', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('showed', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_time', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.PrimaryKeyConstraint('cate_id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('img_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_img_categories_cate_id'), ['cate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_img_categories_cate_name'), ['cate_name'], unique=True)

    op.create_table('images',
    sa.Column('img_id', sa.Integer(), nullable=False),
    sa.Column('img_name', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['img_categories.cate_id'], ),
    sa.PrimaryKeyConstraint('img_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    with op.batch_alter_table('img_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_img_categories_cate_name'))
        batch_op.drop_index(batch_op.f('ix_img_categories_cate_id'))

    op.drop_table('img_categories')
    # ### end Alembic commands ###
